[1.20] pull: do check for blocked registries
cri-o/cri-o pull request #5034
Opened 2021-06-25 16:20 UTC by haircommander

Do not check whether a registry is blocked.  c/image is taking care of
that implicitly when attempting to copy an image.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
or else mirrored registries cannot resolve there
#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
fix a bug where CRI-O prematurely stopped pulling from a blocked registry, even if there was a mirror for that registry it was allowed to pull from.
```

2021-06-25 16:20 UTC, haircommander commented
/cc @mtrmac @vrothberg

2021-06-25 16:26 UTC, haircommander commented
/retest
/cherry-pick release-1.19

2021-06-25 16:39 UTC, mtrmac requested changes
`.Blocked` is also evaluated below in the unqualified-image case. I feel quite strongly that the two should behave the same.

---

IIRC this behavior difference was historically known when implementing the c/image approach, and the CRI-O code here was left around intentionally at that time, though I’m not 100% certain and I might be misremembering. Is there a specific rationale for either that old decision, or the new decision?

(OTOH I don’t feel strongly about preserving this behavior at all, I’m happy to defer decisions about CRI-O behavior stability to CRI-O maintainers. “The code will be simpler and consistent with other c/image users” might be a perfectly good justification.)

2021-06-25 16:47 UTC, mtrmac reviewed
Thanks! Code LGTM, decision whether to change the behavior is up to you.

2021-06-25 16:48 UTC, haircommander commented
> `.Blocked` is also evaluated below in the unqualified-image case. I feel quite strongly that the two should behave the same.
> 
> IIRC this behavior difference was historically known when implementing the c/image approach, and the CRI-O code here was left around intentionally at that time, though I’m not 100% certain and I might be misremembering. Is there a specific rationale for either that old decision, or the new decision?
> 
> (OTOH I don’t feel strongly about preserving this behavior at all, I’m happy to defer decisions about CRI-O behavior stability to CRI-O maintainers. “The code will be simpler and consistent with other c/image users” might be a perfectly good justification.)

My updating this code was mostly because the current behavior wrt the interaction of blocked and mirrored registries is not intuitive to me. I am not married to defering the decision to c/image, but "simpler and consistent" are both also good reasons to do so :)

I removed the .Blocked handling below as well

2021-06-25 16:55 UTC, mtrmac commented
> My updating this code was mostly because the current behavior wrt the interaction of blocked and mirrored registries is not intuitive to me. 

The concept of blocking was created before c/image was aware of it, and IIRC before mirrors were a thing. So it’s quite possible that this before-mirror blocking was just inherited after mirrors, and left around because nobody wanted to affirmatively decide make a change to the behavior, i.e. this might have never been a conscious decision.

2021-06-25 19:50 UTC, haircommander commented
/retest

2021-06-28 08:11 UTC, vrothberg approved these changes
LGTM

2021-06-28 13:22 UTC, haircommander commented
@saschagrunert ptal

2021-06-28 13:25 UTC, saschagrunert approved these changes
/lgtm

2021-06-28 13:26 UTC, merged