bump ocicni to tip and add pod annotations to RuntimeConfig
cri-o/cri-o pull request #7148
Opened 2023-07-20 02:37 UTC by welsper-young

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
The PR allows passing pod annotations to CNI plugins through RuntimeConfig when the pod annotations capability is enabled.
#### Which issue(s) this PR fixes:

Fixes #7122

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
Support pod annotations CNI plugins capability
```

2023-07-20 02:51 UTC, welsper-young commented
/cc @haircommander

2023-07-20 07:24 UTC, saschagrunert requested changes
I'd really like to see an integration test for this.

2023-07-23 12:57 UTC, welsper-young commented
> 

Agree! I will finish it later.

2023-08-07 08:36 UTC, welsper-young commented
/cc @saschagrunert @sohankunkerkar  I add a test for this.

2023-08-07 13:45 UTC, sohankunkerkar reviewed
/ok-to-test

2023-08-07 13:45 UTC, sohankunkerkar commented on test/testdata/log_cni_plugin.sh
> +config=$(cat /dev/stdin)
I think you might want to extend this logic in the [existing](https://github.com/cri-o/cri-o/blob/main/test/cni_plugin_helper.bash) file.

2023-08-07 15:27 UTC, haircommander commented on test/pod_annotations_capability.bats
> +function prepare_cni_plugin() {
instead of copying these helpers, can you put them in test/helpers.bash and reference them from each network.bats and here?

2023-09-27 15:57 UTC, sohankunkerkar commented
/assign @LenkaSeg

2023-09-29 23:25 UTC, closed without merging

2023-09-29 23:25 UTC, sohankunkerkar commented
Closing this in favor of https://github.com/cri-o/cri-o/pull/7342