Update and vendor various dependencies prior to a new release
cri-o/cri-o pull request #7526
Opened 2023-11-30 11:48 UTC by kwilczynski

#### What type of PR is this?

/kind dependency-change
/assign kwilczynski

#### What this PR does / why we need it:

Update various direct build time dependencies prior to a new release. This change also closes several dependency changes that had been open for a while.

Related:

- https://github.com/cri-o/cri-o/pull/7364
- https://github.com/cri-o/cri-o/pull/7368
- https://github.com/cri-o/cri-o/pull/7385
- https://github.com/cri-o/cri-o/pull/7431
- https://github.com/cri-o/cri-o/pull/7451
- https://github.com/cri-o/cri-o/pull/7453
- https://github.com/cri-o/cri-o/pull/7487
- https://github.com/cri-o/cri-o/pull/7489
- https://github.com/cri-o/cri-o/pull/7496
- https://github.com/cri-o/cri-o/pull/7516
- https://github.com/cri-o/cri-o/pull/7523
- https://github.com/containers/conmon-rs/pull/1713
- https://github.com/containers/podman/pull/19873

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

See review comments.

#### Does this PR introduce a user-facing change?

```release-note
None
```

2023-11-30 11:49 UTC, kwilczynski commented on go.mod
> +	github.com/containers/common v0.57.0
This change means that the following Pull Request is no longer needed:

- https://github.com/cri-o/cri-o/pull/7496

2023-11-30 11:51 UTC, kwilczynski commented on go.mod
> +	github.com/checkpoint-restore/go-criu/v7 v7.0.0
This change follows the following upstream update:

- https://github.com/containers/podman/pull/19873

And, when included, would resolve the following build time error:

```
panic: proto: file "stats/stats.proto" is already registered
	previously from: "github.com/checkpoint-restore/go-criu/v6/stats"
	currently from:  "github.com/checkpoint-restore/go-criu/v7/stats"
```

2023-11-30 11:53 UTC, kwilczynski commented on go.mod
> +	github.com/containers/conmon-rs v0.6.2-0.20230920142715-f5a362044a57
This change follows the following upstream change:

- https://github.com/containers/conmon-rs/pull/1713

And, when included, would resolve the following build time error:

```
# github.com/containers/conmon-rs/pkg/client
vendor/github.com/containers/conmon-rs/pkg/client/attach.go:232:19: undefined: util.CopyDetachable
vendor/github.com/containers/conmon-rs/pkg/client/attach.go:429:26: undefined: util.ErrDetach
```

2023-11-30 11:54 UTC, kwilczynski commented on go.mod
> +	github.com/containers/conmon-rs v0.6.2-0.20230920142715-f5a362044a57
To add: this vendors a specific commit for the time being in anticipation of a future new release of conmon-rs.

2023-11-30 12:35 UTC, kwilczynski commented on go.mod
> -	github.com/container-orchestrated-devices/container-device-interface v0.6.0
This change follows the following upstream update:

- https://github.com/cncf-tags/container-device-interface/pull/172

And, when included, would resolve package import issues.

2023-11-30 13:15 UTC, kwilczynski commented
> The linter is not happy, though:
> 
> ```
>   Error: SA1019: otelgrpc.UnaryServerInterceptor is deprecated: Use [NewServerHandler] instead.  (staticcheck)
>   Error: SA1019: otelgrpc.StreamServerInterceptor is deprecated: Use [NewServerHandler] instead.  (staticcheck)
> ```

@saschagrunert, we can fix this later in a follow-up Pull Request.

This might be a larger body of work, and I don't want to mix dependency updates with code refactorings, if possible.

Unless you want this fixed here?

2023-11-30 13:19 UTC, saschagrunert commented
@kwilczynski I'd prefer to fix it within this PR, you can just go for a second commit on top of the dependency changes.

2023-11-30 13:20 UTC, kwilczynski commented
> @kwilczynski I'd prefer to fix it within this PR, you can just go for a second commit on top of the dependency changes.

@saschagrunert, OK! Will do.

2023-12-04 10:26 UTC, kwilczynski commented
/assign hswong3i

2023-12-04 10:29 UTC, saschagrunert approved these changes

2023-12-04 10:45 UTC, kwilczynski commented
/retest-required

2023-12-04 11:31 UTC, saschagrunert commented
/retest

2023-12-04 13:56 UTC, saschagrunert commented
/retest

2023-12-04 15:11 UTC, haircommander commented
@klihub it looks like nri tests are failing: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/cri-o_cri-o/7526/pull-ci-cri-o-cri-o-main-ci-fedora-integration/1731673898904195072/artifacts/fedora-integration/cri-o-gather/artifacts/testout.txt is it due to the update?

2023-12-04 16:00 UTC, klihub commented
@haircommander @kwilczynski Can you guys pull in this commit/fix: https://github.com/klihub/cri-o/commit/53f55e39b514d09caf41bd20f0078d773c34ee1c

That should give

```
Bats 1.9.0
++ bats --jobs 8 --tap nri.bats
1..12
ok 1 run NRI PluginRegistration test
ok 2 run NRI PluginSynchronization test
ok 3 run NRI PodEvents test
ok 4 run NRI ContainerEvents test
ok 5 run NRI MountInjection test
ok 6 run NRI EnvironmentInjection test
ok 7 run NRI AnnotationInjection test
ok 8 run NRI DeviceInjection test
ok 9 run NRI CpusetAdjustment test
ok 10 run NRI MemsetAdjustment test
ok 11 run NRI CpusetAdjustmentUpdate test
ok 12 run NRI MemsetAdjustmentUpdate test
```

2023-12-04 16:05 UTC, klihub requested changes

2023-12-04 16:06 UTC, klihub commented on go.mod
> +	github.com/containerd/nri v0.5.0
And I apologize for not having spotted this in time/earlier....

2023-12-04 16:13 UTC, kwilczynski commented on go.mod
> +	github.com/containerd/nri v0.5.0
@klihub, thank you for taking care of this so promptly! Much appreciated :)

2023-12-04 16:20 UTC, kwilczynski commented
> @haircommander @kwilczynski Can you guys pull in this commit/fix: [klihub@53f55e3](https://github.com/klihub/cri-o/commit/53f55e39b514d09caf41bd20f0078d773c34ee1c)
> 
> That should give
> 
> ```
> Bats 1.9.0
> ++ bats --jobs 8 --tap nri.bats
> 1..12
> ok 1 run NRI PluginRegistration test
> ok 2 run NRI PluginSynchronization test
> ok 3 run NRI PodEvents test
> ok 4 run NRI ContainerEvents test
> ok 5 run NRI MountInjection test
> ok 6 run NRI EnvironmentInjection test
> ok 7 run NRI AnnotationInjection test
> ok 8 run NRI DeviceInjection test
> ok 9 run NRI CpusetAdjustment test
> ok 10 run NRI MemsetAdjustment test
> ok 11 run NRI CpusetAdjustmentUpdate test
> ok 12 run NRI MemsetAdjustmentUpdate test
> ```

Done. Completed in https://github.com/cri-o/cri-o/pull/7526/commits/c80c3aa5f5d557a6fd790f64dca77bc8ae9800fd.

Thank you a bunch for help, @klihub! :+1:

2023-12-04 16:24 UTC, haircommander commented
/lgtm

2023-12-04 16:38 UTC, haircommander commented
hm need a [docs validation update](https://github.com/cri-o/cri-o/actions/runs/7089610098/job/19294847996?pr=7526)

2023-12-04 16:39 UTC, kwilczynski commented
> hm need a [docs validation update](https://github.com/cri-o/cri-o/actions/runs/7089610098/job/19294847996?pr=7526)

@haircommander, will take care of it.

2023-12-04 16:41 UTC, kwilczynski commented
I also took the liberty of including the following update:

- https://github.com/cri-o/cri-o/pull/7547

Especially as our tireless bot has already noticed a recent update to this dependency.

2023-12-04 16:57 UTC, klihub commented
/lgtm cancel

2023-12-04 17:22 UTC, sohankunkerkar approved these changes
/lgtm

2023-12-04 18:39 UTC, haircommander commented
/override ci/prow/ci-e2e-conmonrs

2023-12-04 19:46 UTC, haircommander commented
/retest

2023-12-05 04:53 UTC, sohankunkerkar commented
/retest

2023-12-05 05:56 UTC, merged