Remove `registries` config and `--registry` option
cri-o/cri-o pull request #8194
Opened 2024-05-17 00:04 UTC by bitoku

#### What type of PR is this?

/kind cleanup
/kind deprecation

#### What this PR does / why we need it:

This PR removes `registries` config and `--registry` option

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

See #8161 for the context.

#### Does this PR introduce a user-facing change?

```release-note
Remove `registries` config in `crio.image` and `--registry` option which have been already deprecated.
```

2024-05-17 03:31 UTC, kwilczynski commented
/ok-to-test

2024-05-17 06:44 UTC, saschagrunert commented on Makefile
> +docs-generation: bin/crio
It may be possible that we break consumers with that.

2024-05-17 06:45 UTC, saschagrunert requested changes

2024-05-17 06:45 UTC, saschagrunert commented on Makefile
> +docs-generation: bin/crio
Let's revert that, it may break existing users.

2024-05-17 15:14 UTC, kwilczynski commented
/test ci-cgroupv2-integration

2024-05-20 12:23 UTC, kwilczynski commented
/approve
/lgtm

2024-05-23 08:55 UTC, kwilczynski commented
/close

2024-05-23 08:55 UTC, kwilczynski commented
/reopen

2024-05-23 08:55 UTC, kwilczynski commented
/retest

2024-05-23 09:09 UTC, kwilczynski commented
/test ci-fedora-kata

2024-05-26 13:56 UTC, kwilczynski commented
/retest

2024-05-29 08:58 UTC, kwilczynski commented
/approve
/lgtm

2024-05-29 08:59 UTC, kwilczynski commented
@cri-o/cri-o-maintainers, can you give this another pass? Thank you!

2024-05-29 09:00 UTC, saschagrunert approved these changes

2024-05-31 10:30 UTC, kwilczynski commented
/retest

2024-05-31 17:31 UTC, kwilczynski commented
/test ci-cgroupv2-integration

2024-05-31 18:31 UTC, merged